'use client';
import {useEffect,useState} from 'react';

const ui={page:{minHeight:'100vh',padding:24,color:'#f6ead3',fontFamily:'Arial,Microsoft YaHei,sans-serif',background:'radial-gradient(circle at 82% 0,#3c2b12 0,#121417 38%,#060708 100%)'},wrap:{maxWidth:1180,margin:'0 auto'},header:{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,marginBottom:18},brand:{display:'flex',alignItems:'center',gap:14},logo:{width:48,height:48,borderRadius:16,display:'grid',placeItems:'center',fontWeight:900,color:'#17120a',background:'linear-gradient(135deg,#fff0b8,#d59d3a 60%,#7b4d14)',boxShadow:'0 12px 36px rgba(213,157,58,.28)'},panel:{background:'rgba(18,20,24,.78)',border:'1px solid rgba(225,190,116,.22)',borderRadius:24,boxShadow:'0 18px 70px rgba(0,0,0,.46)',backdropFilter:'blur(18px)'},card:{padding:18,marginBottom:16},grid:{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:14},btn:{border:0,borderRadius:14,padding:'11px 16px',background:'linear-gradient(135deg,#f4d78b,#a87222)',color:'#161008',fontWeight:900,cursor:'pointer'},ghost:{border:'1px solid rgba(225,190,116,.24)',borderRadius:14,padding:'10px 14px',background:'rgba(255,255,255,.05)',color:'#f6ead3',cursor:'pointer',textDecoration:'none'},table:{width:'100%',borderCollapse:'collapse'},td:{borderBottom:'1px solid rgba(225,190,116,.12)',padding:12,fontSize:14,verticalAlign:'top'},muted:{color:'#b7aa91'},code:{fontSize:52,letterSpacing:8,margin:'8px 0',color:'#f4d78b'}};
function Card(p){return <section style={{...ui.panel,...ui.card,...(p.style||{})}}>{p.children}</section>}
function Stat({label,value,sub}){return <Card><div style={ui.muted}>{label}</div><h2 style={{margin:'8px 0 4px'}}>{value}</h2>{sub&&<small style={ui.muted}>{sub}</small>}</Card>}
export default function UsersPage(){
 const [code,setCode]=useState(null),[data,setData]=useState(null),[msg,setMsg]=useState('');
 async function load(){const [c,s]=await Promise.all([fetch('/api/access-code',{cache:'no-store'}).then(r=>r.json()),fetch('/api/client-stats',{cache:'no-store'}).then(r=>r.json())]);setCode(c);setData(s)}
 useEffect(()=>{load()},[]);
 async function copy(){await navigator.clipboard?.writeText(code?.code||'');setMsg('验证码已复制')}
 const stats=data?.stats||{};
 return <main style={ui.page}><div style={ui.wrap}><header style={ui.header}><div style={ui.brand}><div style={ui.logo}>龙</div><div><h1 style={{margin:0}}>用户统计 / 动态验证码</h1><p style={{...ui.muted,margin:'6px 0 0'}}>不做收费等级，只做简单使用准入和匿名数据统计。</p></div></div><a style={ui.ghost} href='/'>返回主后台</a></header><Card><h2>今日动态验证码</h2><p style={ui.muted}>用户在插件里输入这个验证码后即可正常使用。验证码每天自动变化。</p><div style={ui.code}>{code?.code||'------'}</div><p>过期时间：{code?.expiresAt?new Date(code.expiresAt).toLocaleString():'-'}</p><button style={ui.btn} onClick={copy}>复制验证码</button> <button style={ui.ghost} onClick={load}>刷新</button><p>{msg}</p></Card><div style={ui.grid}><Stat label='总使用者' value={stats.totalClients??0} sub='匿名设备数'/><Stat label='今日活跃' value={stats.activeToday??0}/><Stat label='7天活跃' value={stats.active7d??0}/><Stat label='事件总数' value={stats.totalEvents??0}/></div><div style={ui.grid}><Stat label='打开插件' value={stats.opens??0}/><Stat label='连接次数' value={stats.connects??0}/><Stat label='测速次数' value={stats.speedTests??0}/><Stat label='验证成功/失败' value={`${stats.verifySuccess??0}/${stats.verifyFailed??0}`}/></div><Card><h2>常用节点</h2><table style={ui.table}><thead><tr><th style={{...ui.td,textAlign:'left'}}>节点</th><th style={{...ui.td,textAlign:'left'}}>使用次数</th></tr></thead><tbody>{(data?.topNodes||[]).map(x=><tr key={x.name}><td style={ui.td}>{x.name}</td><td style={ui.td}>{x.count}</td></tr>)}</tbody></table></Card><Card><h2>最近使用者</h2><table style={ui.table}><thead><tr>{['匿名ID','插件版本','首次使用','最后活跃'].map(h=><th key={h} style={{...ui.td,textAlign:'left'}}>{h}</th>)}</tr></thead><tbody>{(data?.clients||[]).slice(0,50).map(x=><tr key={x.client_id}><td style={ui.td}>{x.client_id}</td><td style={ui.td}>{x.plugin_version||'-'}</td><td style={ui.td}>{x.first_seen_at?new Date(x.first_seen_at).toLocaleString():'-'}</td><td style={ui.td}>{x.last_seen_at?new Date(x.last_seen_at).toLocaleString():'-'}</td></tr>)}</tbody></table></Card><Card><h2>最近事件</h2><table style={ui.table}><thead><tr>{['时间','匿名ID','事件','节点'].map(h=><th key={h} style={{...ui.td,textAlign:'left'}}>{h}</th>)}</tr></thead><tbody>{(data?.events||[]).slice(0,80).map((x,i)=><tr key={i}><td style={ui.td}>{x.created_at?new Date(x.created_at).toLocaleString():'-'}</td><td style={ui.td}>{x.client_id}</td><td style={ui.td}>{x.event}</td><td style={ui.td}>{x.node_name||'-'}</td></tr>)}</tbody></table></Card></div></main>
}
