'use client';
import {useEffect,useState} from 'react';
const S={page:{minHeight:'100vh',background:'radial-gradient(circle at 80% 0,#423015 0,#101318 42%,#050607 100%)',color:'#f7ead0',fontFamily:'Arial,Microsoft YaHei,sans-serif',padding:24},wrap:{maxWidth:1040,margin:'0 auto'},top:{display:'flex',alignItems:'center',justifyContent:'space-between',gap:16,marginBottom:18},brand:{display:'flex',alignItems:'center',gap:14},logo:{width:52,height:52,borderRadius:18,display:'grid',placeItems:'center',fontSize:26,fontWeight:900,color:'#17120a',background:'linear-gradient(135deg,#fff1bb,#d59d3a 60%,#7b4d14)',boxShadow:'0 16px 42px rgba(213,157,58,.32)'},pill:{border:'1px solid rgba(225,190,116,.26)',borderRadius:999,padding:'9px 14px',background:'rgba(255,255,255,.05)',color:'#d8c392',fontSize:13},grid:{display:'grid',gridTemplateColumns:'1.1fr .9fr',gap:16},panel:{background:'linear-gradient(180deg,rgba(24,27,33,.9),rgba(12,14,18,.86))',border:'1px solid rgba(225,190,116,.22)',borderRadius:26,boxShadow:'0 22px 80px rgba(0,0,0,.48)',padding:24,backdropFilter:'blur(18px)'},cardTitle:{margin:'0 0 8px',fontSize:24},muted:{color:'#b7aa91',lineHeight:1.7},label:{display:'block',margin:'16px 0 8px',fontSize:13,color:'#d8c392',fontWeight:800},input:{height:48,border:'1px solid rgba(225,190,116,.28)',borderRadius:15,background:'rgba(255,255,255,.065)',color:'#fff',padding:'0 14px',outline:'none',width:'100%',fontSize:15},btn:{height:48,border:0,borderRadius:15,padding:'0 20px',background:'linear-gradient(135deg,#f6dd96,#b27a23)',color:'#17120a',fontWeight:900,cursor:'pointer',boxShadow:'0 12px 28px rgba(178,122,35,.22)'},ghost:{height:48,border:'1px solid rgba(225,190,116,.25)',borderRadius:15,padding:'0 18px',background:'rgba(255,255,255,.045)',color:'#f7ead0',fontWeight:800,cursor:'pointer'},row:{display:'flex',gap:10,alignItems:'center',flexWrap:'wrap',marginTop:18},ok:{color:'#7dff9e'},bad:{color:'#ff9b9b'},box:{border:'1px solid rgba(225,190,116,.16)',borderRadius:18,background:'rgba(255,255,255,.035)',padding:16,marginTop:14},code:{fontSize:34,letterSpacing:6,fontWeight:900,color:'#f4d78b'},link:{color:'#f4d78b',textDecoration:'none'}};
function Notice({msg}){if(!msg)return null;const ok=msg.includes('成功')||msg.includes('ok');return <p style={ok?S.ok:S.bad}>{msg}</p>}
export default function Page(){
 const [email,setEmail]=useState(''),[loginSecret,setLoginSecret]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[info,setInfo]=useState(null),[codeInfo,setCodeInfo]=useState(null),[code,setCode]=useState(''),[expiresAt,setExpiresAt]=useState(''),[codeMsg,setCodeMsg]=useState('');
 async function load(){const a=await fetch('/api/admin-account',{cache:'no-store'}).then(r=>r.json()).catch(()=>null);setInfo(a);if(a?.email)setEmail(a.email);const c=await fetch('/api/access-settings',{cache:'no-store'}).then(r=>r.json()).catch(()=>null);setCodeInfo(c);if(c?.current?.code)setCode(c.current.code);if(c?.current?.expiresAt)setExpiresAt(c.current.expiresAt.slice(0,16));}
 useEffect(()=>{load()},[]);
 async function save(){setLoading(true);setMsg('保存中...');const r=await fetch('/api/admin-account',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,loginSecret})});const j=await r.json().catch(()=>({}));setMsg(j.message||String(r.status));setLoading(false);if(r.ok){setLoginSecret('');load();}}
 async function saveCode(){setCodeMsg('保存中...');const iso=expiresAt?new Date(expiresAt).toISOString():'';const r=await fetch('/api/access-settings',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code,expiresAt:iso,enabled:true,note:'后台页面设置'})});const j=await r.json().catch(()=>({}));setCodeMsg(j.message||String(r.status));load();}
 return <main style={S.page}><div style={S.wrap}><header style={S.top}><div style={S.brand}><div style={S.logo}>龙</div><div><h1 style={{margin:0}}>玉龙VPN 2.0 安全设置</h1><p style={{...S.muted,margin:'5px 0 0'}}>账号登录与动态验证码统一管理</p></div></div><span style={S.pill}>SECURE · CLEAN · ADMIN</span></header><section style={S.grid}><div style={S.panel}><h2 style={S.cardTitle}>后台账号密码</h2><p style={S.muted}>修改后台登录邮箱和登录口令。保存成功后，请退出后台，再使用新信息重新登录。</p><label style={S.label}>后台登录邮箱</label><input style={S.input} value={email} onChange={e=>setEmail(e.target.value)} placeholder='admin@example.com'/><label style={S.label}>新登录口令</label><input style={S.input} value={loginSecret} onChange={e=>setLoginSecret(e.target.value)} placeholder='至少 6 位，留空不会保存'/><div style={S.row}><button style={S.btn} onClick={save} disabled={loading}>{loading?'保存中...':'保存账号设置'}</button><button style={S.ghost} onClick={load}>刷新当前信息</button><a style={S.link} href='/'>返回主后台</a></div><Notice msg={msg}/><div style={S.box}><b>当前状态</b><p style={S.muted}>当前账号：{info?.email||'-'}</p><p style={S.muted}>来源：{info?.source||'-'}　更新时间：{info?.updatedAt||'-'}</p></div></div><div style={S.panel}><h2 style={S.cardTitle}>动态验证码</h2><p style={S.muted}>这里可以快速修改插件和 APK 使用的 6 位动态验证码。</p><div style={S.box}><div style={S.muted}>当前验证码</div><div style={S.code}>{codeInfo?.current?.code||'------'}</div><p style={S.muted}>过期时间：{codeInfo?.current?.expiresAt||'-'}</p></div><label style={S.label}>新的 6 位验证码</label><input style={S.input} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} placeholder='123456'/><label style={S.label}>过期时间</label><input style={S.input} type='datetime-local' value={expiresAt} onChange={e=>setExpiresAt(e.target.value)}/><div style={S.row}><button style={S.btn} onClick={saveCode}>保存验证码</button><button style={S.ghost} onClick={load}>刷新</button></div><Notice msg={codeMsg}/></div></section></div></main>
}
