'use client';
import {useEffect,useState} from 'react';

const navs=['控制台','节点管理','配置发布','公告管理','域名/CDN','系统日志','系统设置'];
const s={wrap:{minHeight:'100vh',background:'#f3f6fb',fontFamily:'Arial,Microsoft YaHei,sans-serif',color:'#172033'},login:{minHeight:'100vh',display:'grid',placeItems:'center'},box:{width:420,background:'#fff',borderRadius:18,padding:30,border:'1px solid #dfe7f3'},input:{width:'100%',height:42,marginTop:10,padding:'0 12px'},btn:{border:0,borderRadius:10,padding:'10px 14px',background:'#1769ff',color:'#fff'},shell:{display:'flex',minHeight:'100vh'},side:{width:240,background:'#12335f',color:'#fff',padding:22},nav:{display:'block',width:'100%',margin:'8px 0',border:0,borderRadius:10,padding:12,color:'#fff',textAlign:'left'},main:{flex:1,padding:26},card:{background:'#fff',border:'1px solid #dfe7f3',borderRadius:16,padding:18,marginBottom:16},grid:{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14},table:{width:'100%',borderCollapse:'collapse'},cell:{borderBottom:'1px solid #edf2f7',padding:10}};

function NodeTable({nodes}){return <table style={s.table}><thead><tr>{['节点','地区','地址','端口','延迟','状态'].map(h=><th key={h} style={s.cell}>{h}</th>)}</tr></thead><tbody>{nodes.map(n=><tr key={n.id}><td style={s.cell}>{n.name}</td><td style={s.cell}>{n.region}</td><td style={s.cell}>{n.address}</td><td style={s.cell}>{n.port}</td><td style={s.cell}>{n.delay} ms</td><td style={s.cell}>{n.status}</td></tr>)}</tbody></table>}

export default function Page(){
 const [ok,setOk]=useState(false),[email,setEmail]=useState(''),[pwd,setPwd]=useState(''),[err,setErr]=useState(''),[tab,setTab]=useState('控制台');
 const [health,setHealth]=useState(null),[nodes,setNodes]=useState([]),[notices,setNotices]=useState([]),[config,setConfig]=useState(null);
 async function login(){setErr('');const r=await fetch('/api/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,password:pwd})});if(!r.ok){setErr('邮箱或密码错误');return;}setOk(true)}
 useEffect(()=>{if(!ok)return;Promise.all([fetch('/api/health').then(r=>r.json()),fetch('/api/nodes').then(r=>r.json()),fetch('/api/notices').then(r=>r.json()),fetch('/api/config').then(r=>r.json())]).then(([h,n,no,c])=>{setHealth(h);setNodes(n.items||[]);setNotices(no.items||[]);setConfig(c)})},[ok]);
 if(!ok)return <div style={s.wrap}><main style={s.login}><section style={s.box}><h1>玉龙VPN 管理后台</h1><p>邮箱：admin@yulongvpn.local<br/>密码：yulongvpn2026</p><input style={s.input} value={email} onChange={e=>setEmail(e.target.value)} placeholder="邮箱"/><input style={s.input} value={pwd} onChange={e=>setPwd(e.target.value)} placeholder="密码" type="password"/><p style={{color:'#c62828'}}>{err}</p><button style={{...s.btn,width:'100%'}} onClick={login}>登录后台</button></section></main></div>;
 return <div style={s.wrap}><div style={s.shell}><aside style={s.side}><h2>玉龙VPN</h2><p>新一代配置中心 v7</p>{navs.map(x=><button key={x} onClick={()=>setTab(x)} style={{...s.nav,background:tab===x?'#1769ff':'rgba(255,255,255,.12)'}}>{x}</button>)}</aside><main style={s.main}><h1>{tab}</h1>{tab==='控制台'&&<><div style={s.grid}><div style={s.card}>后端状态<h2>{health?.status||'loading'}</h2></div><div style={s.card}>节点数量<h2>{nodes.length}</h2></div><div style={s.card}>配置版本<h2>v{config?.version||'-'}</h2></div><div style={s.card}>公告数量<h2>{notices.length}</h2></div></div><section style={s.card}><h2>节点状态</h2><NodeTable nodes={nodes}/></section></>}{tab==='节点管理'&&<section style={s.card}><h2>节点管理</h2><p>数据来自 /api/nodes。</p><NodeTable nodes={nodes}/></section>}{tab==='配置发布'&&<section style={s.card}><h2>配置发布</h2><p>插件配置源：/api/config</p><pre>{JSON.stringify(config,null,2)}</pre></section>}{tab==='公告管理'&&<section style={s.card}><h2>公告管理</h2>{notices.map(n=><p key={n.id}><b>{n.title}</b> · {n.status}<br/>{n.content}</p>)}</section>}{tab==='域名/CDN'&&<section style={s.card}><h2>域名/CDN</h2><p>当前主源：Vercel API</p><p>后续可接 GitHub Raw / CloudFront / 数据库。</p></section>}{tab==='系统日志'&&<section style={s.card}><h2>系统日志</h2><p>已修复：登录校验、菜单点击、配置版本显示。</p></section>}{tab==='系统设置'&&<section style={s.card}><h2>系统设置</h2><p>生产环境建议把后台密码放到 Vercel 环境变量。</p></section>}</main></div></div>
}
