'use client';
import {useEffect,useState} from 'react';

const blank={id:'',title:'',type:'系统通知',status:'已发布',content:'',priority:10};
const s={page:{minHeight:'100vh',background:'linear-gradient(135deg,#08090b,#111315 55%,#08090b)',color:'#f4efe6',fontFamily:'Arial,Microsoft YaHei,sans-serif',padding:24},panel:{maxWidth:1100,margin:'0 auto',background:'rgba(24,25,27,.76)',border:'1px solid rgba(218,190,130,.20)',borderRadius:22,padding:22,boxShadow:'0 18px 70px rgba(0,0,0,.42)'},input:{height:42,border:'1px solid rgba(218,190,130,.24)',borderRadius:12,background:'rgba(255,255,255,.06)',color:'#fff',padding:'0 12px'},area:{minHeight:90,border:'1px solid rgba(218,190,130,.24)',borderRadius:12,background:'rgba(255,255,255,.06)',color:'#fff',padding:12},btn:{border:0,borderRadius:12,padding:'10px 14px',background:'linear-gradient(135deg,#f0d9a0,#b98b3c)',color:'#15110b',fontWeight:700,cursor:'pointer'},ghost:{border:'1px solid rgba(218,190,130,.24)',borderRadius:12,padding:'10px 14px',background:'rgba(255,255,255,.05)',color:'#f4efe6',cursor:'pointer'},grid:{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:10},td:{borderBottom:'1px solid rgba(218,190,130,.12)',padding:10,fontSize:14},pre:{background:'#07090c',borderRadius:14,padding:14,color:'#d8f6ff',whiteSpace:'pre-wrap'}};
export default function NoticesPage(){
 const [items,setItems]=useState([]),[form,setForm]=useState(blank),[msg,setMsg]=useState(''),[raw,setRaw]=useState(null);
 async function load(){const r=await fetch('/api/notices',{cache:'no-store'});const j=await r.json();setRaw(j);setItems(j.items||[])}
 useEffect(()=>{load()},[]);
 async function save(){setMsg('保存中...');const body={...form,_method:form._edit?'update':undefined};const r=await fetch('/api/notices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok){setMsg(j.message||'保存失败：请先创建 yulong_notices 表');return;}setMsg('已保存，插件刷新后会显示');setForm(blank);load()}
 async function remove(n){if(!confirm('删除通知 '+n.title+' ?'))return;const r=await fetch('/api/notices',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({_method:'remove',id:n.id})});setMsg(r.ok?'已删除':'删除失败');load()}
 return <main style={s.page}><section style={s.panel}><h1>玉龙VPN 前台通知管理</h1><p>状态为“已发布”的内容，会显示在插件顶部通知条。接口：/api/notices?public=1</p><p>数据源：{raw?.source||'-'}；可编辑：{raw?.editable?'是':'否'}</p><div style={s.grid}>{['id','title','type','status','priority'].map(k=><input key={k} style={s.input} value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k}/>)}</div><textarea style={{...s.area,width:'100%',margin:'10px 0'}} value={form.content||''} onChange={e=>setForm({...form,content:e.target.value})} placeholder='通知内容，例如：今晚 23:00 节点维护，建议使用日本01。'/><button style={s.btn} onClick={save}>{form._edit?'保存修改':'新增通知'}</button> <button style={s.ghost} onClick={()=>setForm(blank)}>清空</button> <button style={s.ghost} onClick={load}>刷新</button> <a style={{color:'#f0d9a0',marginLeft:12}} href='/'>返回后台</a><p>{msg}</p><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr>{['标题','类型','状态','内容','优先级','操作'].map(h=><th key={h} style={{...s.td,textAlign:'left',color:'#d9bd79'}}>{h}</th>)}</tr></thead><tbody>{items.map(n=><tr key={n.id}><td style={s.td}>{n.title}</td><td style={s.td}>{n.type}</td><td style={s.td}>{n.status}</td><td style={s.td}>{n.content}</td><td style={s.td}>{n.priority}</td><td style={s.td}><button style={s.ghost} onClick={()=>setForm({...n,_edit:true})}>修改</button> <button style={s.ghost} onClick={()=>remove(n)}>删除</button></td></tr>)}</tbody></table><h3>接口返回</h3><pre style={s.pre}>{JSON.stringify(raw,null,2)}</pre></section></main>}
